produit_index:
    path:     /lsp
    defaults: { _controller: "FrontBonPlanBundle:Produit:index" }
    methods:  GET

produit_show:
    path:     /{idproduit}/showpr
    defaults: { _controller: "FrontBonPlanBundle:Produit:show" }
    methods:  GET

produit_new:
    path:     /newPr
    defaults: { _controller: "FrontBonPlanBundle:Produit:new" }
    methods:  [GET, POST]

produit_edit:
    path:     /{idproduit}/editpr
    defaults: { _controller: "FrontBonPlanBundle:Produit:edit" }
    methods:  [GET, POST]

produit_delete:
    path:     /{idproduit}/deletepr
    defaults: { _controller: "FrontBonPlanBundle:Produit:delete" }
    methods:  DELETE




