publicite_index:
    path:     /
    defaults: { _controller: "FrontBonPlanBundle:Publicite:index" }
    methods:  GET

publicite_show:
    path:     /{idpublicite}/show
    defaults: { _controller: "FrontBonPlanBundle:Publicite:show" }
    methods:  GET

publicite_new:
    path:     /new
    defaults: { _controller: "FrontBonPlanBundle:Publicite:new" }
    methods:  [GET, POST]

publicite_edit:
    path:     /{idpublicite}/edit
    defaults: { _controller: "FrontBonPlanBundle:Publicite:edit" }
    methods:  [GET, POST]

publicite_delete:
    path:     /{idpublicite}/delete
    defaults: { _controller: "FrontBonPlanBundle:Publicite:delete" }
    methods:  DELETE
