reserver_index:
    path:     /
    defaults: { _controller: "FrontBonPlanBundle:Reserver:index" }
    methods:  GET

reserver_show:
    path:     /{idreservation}/show
    defaults: { _controller: "FrontBonPlanBundle:Reserver:show" }
    methods:  GET

reserver_new:
    path:     /new
    defaults: { _controller: "FrontBonPlanBundle:Reserver:new" }
    methods:  [GET, POST]

reserver_edit:
    path:     /{idreservation}/edit
    defaults: { _controller: "FrontBonPlanBundle:Reserver:edit" }
    methods:  [GET, POST]

reserver_delete:
    path:     /{idreservation}/delete
    defaults: { _controller: "FrontBonPlanBundle:Reserver:delete" }
    methods:  DELETE
