front_bon_plan:
    resource: "@FrontBonPlanBundle/Resources/config/routing.yml"
    prefix:   /
back_bon_plan_back_homepage:
    resource: "@BackBonPlanBackBundle/Resources/config/routing.yml"
    prefix:   /


app:
    resource: '@AppBundle/Controller/'
    type: annotation
