
tf_user:
    resource: "@tfUserBundle/Resources/config/routing.yml"
    prefix:   /prestataire
front_bon_plan:
    resource: "@FrontBonPlanBundle/Resources/config/routing.yml"
    prefix:   /
back_bon_plan_back_homepage:
    resource: "@BackBonPlanBackBundle/Resources/config/routing.yml"
    prefix:   /admin


app:
    resource: '@AppBundle/Controller/'
    type: annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
