api_homepage:
    path:     /
    defaults: { _controller: ApiBundle:Default:index }
get_User:
    path:     /user/{login}/{password}
    defaults: { _controller: ApiBundle:UserApi:getUser}
get_AllUser:
    path:     /users
    defaults: { _controller: ApiBundle:UserApi:getAllUsers}
get_Articles:
    path:     /Articles
    defaults: { _controller: ApiBundle:ArticleApi:allArticle}
new_Article:
    path:     /newArticle/{iduser}/{idr}/{idc}/{titre}/{description}/{imagename}/{adresse}
    defaults: { _controller: ApiBundle:ArticleApi:newArticle}
get_DetailArticle:
    path:     /detailsarticle/{idArticle}
    defaults: { _controller: ApiBundle:ArticleApi:article}
get_articlesByUser:
    path:     /articlebyuser/{idUser}
    defaults: { _controller: ApiBundle:ArticleApi:articleByUser}
get_allRegions:
    path:     /allRegions
    defaults: { _controller: ApiBundle:RegionApi:getAllRegion}
get_Calegories:
    path:     /allCalegories
    defaults: { _controller: ApiBundle:CategorieArticleApi:getAllCategorieaArticle}

get_Produits:
    path:     /produits
    defaults: { _controller: ApiBundle:ArticleApi:allProduit}
new_Produits:
    path:     /newproduit/{idprestataire}/{nom}/{qte}/{prix}/{detail}/{imagename}/{adresse}
    defaults: { _controller: ApiBundle:ArticleApi:newProduit}
get_DetailProduit:
    path:     /detailsproduit/{idpoduit}
    defaults: { _controller: ApiBundle:ArticleApi:produit}
get_produisByPrest:
    path:     /produitsbyprest/{idprestataire}
    defaults: { _controller: ApiBundle:ArticleApi:produitByPrest}



