api_homepage:
    path:     /
    defaults: { _controller: ApiBundle:Default:index }
get_User:
    path:     /user/{login}/{password}
    defaults: { _controller: ApiBundle:UserApi:getUser}
get_Article:
    path:     /Article
    defaults: { _controller: ApiBundle:ArticleApi:getAllArticle}



