front_bon_plan_evennement:
    resource: "@FrontBonPlanBundle/Resources/config/routing/evennement.yml"
    prefix:   /evennement


front_bon_plan_reserver:
        resource: "@FrontBonPlanBundle/Resources/config/routing/reserver.yml"
        prefix:   /reserver

front_bon_plan_categoriearticle:
        resource: "@FrontBonPlanBundle/Resources/config/routing/categoriearticle.yml"
        prefix:   /categoriearticle

front_bon_plan_categorieevenement:
        resource: "@FrontBonPlanBundle/Resources/config/routing/categorieevenement.yml"
        prefix:   /categorieevenement

articles_search:
    path:     /search
    defaults: { _controller: FrontBonPlanBundle:Default:search }

articles_categorie:
    path:     /categorie/{id}
    defaults: { _controller: FrontBonPlanBundle:Default:articlesCategory }




front_bon_plan_homepage:
    path:     /index
    defaults: { _controller: FrontBonPlanBundle:Default:index }
front_bon_plan_user:
    path:     /user
    defaults: { _controller: FrontBonPlanBundle:User:user }
front_bon_plan_menu:
    path:     /menu
    defaults: { _controller: FrontBonPlanBundle:Default:menu }
front_bon_plan_blog:
    path:     /blog
    defaults: { _controller: FrontBonPlanBundle:Default:blog }
front_bon_plan_single:
    path:     /single/{id}
    defaults: { _controller: FrontBonPlanBundle:Default:single }
front_bon_plan_singleProduit:
    path:     /singleProduit/{id}
    defaults: { _controller: FrontBonPlanBundle:Default:singleProduit }
front_bon_plan_events:
    path:     /events/{id}
    defaults: { _controller: FrontBonPlanBundle:Default:events }
front_bon_plan_contact:
    path:     /contact
    defaults: { _controller: FrontBonPlanBundle:Contact:index }
front_bon_plan_success:
    path:     /success
    defaults: { _controller: FrontBonPlanBundle:Contact:success }
front_bon_plan_login:
    path:     /login
    defaults: { _controller: FOSUserBundle:Security:login }
fos_user_registration_register:
    path:     /register
    defaults: { _controller: FOSUserBundle:Registration:register }
rating:
    path:     /rating
    defaults: { _controller: FrontBonPlanBundle:Default:rating }


reserver_index:
    path:     /
    defaults: { _controller: "FrontBonPlanBundle:Reserver:index" }
    methods:  GET

reserver_show:
    path:     /{idreservation}/showReservation
    defaults: { _controller: "FrontBonPlanBundle:Reserver:show" }
    methods:  GET

reserver_new:
    path:     /newReservation/{id}
    defaults: { _controller: "FrontBonPlanBundle:Reserver:new" }
    methods:  [GET, POST]

reserver_edit:
    path:     /{idreservation}/editReservation
    defaults: { _controller: "FrontBonPlanBundle:Reserver:edit" }
    methods:  [GET, POST]

reserver_delete:
    path:     /{idreservation}/deleteReservation
    defaults: { _controller: "FrontBonPlanBundle:Reserver:delete" }
    methods:  DELETE

get_Evennement:
    path:     /getAllEvennement
    defaults: { _controller: FrontBonPlanBundle:Evennement:getAllEvennement}

New_Res:
    path:     /nouvelleReservation/{idevent}/{iduser}/{nbrePlace}
    defaults: { _controller: FrontBonPlanBundle:Reserver:createreservation}





