front_bon_plan_evennement:
    resource: "@FrontBonPlanBundle/Resources/config/routing/evennement.yml"
    prefix:   /evennement

front_bon_plan_homepage:
    path:     /index
    defaults: { _controller: FrontBonPlanBundle:Default:index }
front_bon_plan_menu:
    path:     /menu
    defaults: { _controller: FrontBonPlanBundle:Default:menu }
front_bon_plan_blog:
    path:     /blog
    defaults: { _controller: FrontBonPlanBundle:Default:blog }
front_bon_plan_single:
    path:     /single
    defaults: { _controller: FrontBonPlanBundle:Default:single }
front_bon_plan_events:
    path:     /events
    defaults: { _controller: FrontBonPlanBundle:Default:events }
front_bon_plan_contact:
    path:     /contact
    defaults: { _controller: FrontBonPlanBundle:Default:contact }
front_bon_plan_login:
    path:     /login
    defaults: { _controller: FOSUserBundle:Security:login }
fos_user_registration_register:
    path:     /register
    defaults: { _controller: FOSUserBundle:Registration:register }

evennement_index:
    path:     /listEvenements
    defaults: { _controller: "FrontBonPlanBundle:Evennement:index" }
    methods:  GET

evennement_show:
    path:     /{idev}/show
    defaults: { _controller: "FrontBonPlanBundle:Evennement:show" }
    methods:  GET

evennement_new:
    path:     /new
    defaults: { _controller: "FrontBonPlanBundle:Evennement:new" }
    methods:  [GET, POST]

evennement_edit:
    path:     /{idev}/edit
    defaults: { _controller: "FrontBonPlanBundle:Evennement:edit" }
    methods:  [GET, POST]

evennement_delete:
    path:     /{idev}/delete
    defaults: { _controller: "FrontBonPlanBundle:Evennement:delete" }
    methods:  DELETE

