back_bon_plan_back_homepage:
    path:     /
    defaults: { _controller: BackBonPlanBackBundle:Default:index }
bonplan_admin_template:
    path:     /temp
    defaults: { _controller: BackBonPlanBackBundle:Default:index }
bonplan_prestataire_template:
    path:     /prestataire
    defaults: { _controller: BackBonPlanBackBundle:Default:prestataire }

front_bon_plan_categoriearticle:
        resource: "@FrontBonPlanBundle/Resources/config/routing/categoriearticle.yml"
        prefix:   /categoriearticle

front_bon_plan_categorieevenement:
        resource: "@FrontBonPlanBundle/Resources/config/routing/categorieevenement.yml"
        prefix:   /categorieevenement

listarticles_admin:
    path:     /listArticle
    defaults: { _controller: "FrontBonPlanBundle:Article:indexAdmin" }
    methods:  GET
article_activer:
    path:     /{idarticle}/activerArticle
    defaults: { _controller: "FrontBonPlanBundle:Article:activer" }
    methods:  [GET, POST]
article_desactiver:
    path:     /{idarticle}/desactiverArticle
    defaults: { _controller: "FrontBonPlanBundle:Article:desactiver" }
    methods:  [GET, POST]
article_details:
    path:     /{idarticle}/detailsArticle
    defaults: { _controller: "FrontBonPlanBundle:Article:details" }
    methods:  [GET, POST]

categorieevenement_index:
    path:     /listCategorieEvennement
    defaults: { _controller: "FrontBonPlanBundle:Categorieevenement:index" }
    methods:  GET

categorieevenement_show:
    path:     /{idcatev}/showEvennement
    defaults: { _controller: "FrontBonPlanBundle:Categorieevenement:show" }
    methods:  GET

categorieevenement_new:
    path:     /newEvennement
    defaults: { _controller: "FrontBonPlanBundle:Categorieevenement:new" }
    methods:  [GET, POST]

categorieevenement_edit:
    path:     /{idcatev}/editEvennement
    defaults: { _controller: "FrontBonPlanBundle:Categorieevenement:edit" }
    methods:  [GET, POST]

categorieevenement_delete:
    path:     /{idcatev}/deleteEvennement
    defaults: { _controller: "FrontBonPlanBundle:Categorieevenement:delete" }
    methods:  DELETE


categoriearticle_index:
    path:     /listCategorieArticle
    defaults: { _controller: "FrontBonPlanBundle:Categoriearticle:index" }
    methods:  GET

categoriearticle_show:
    path:     /{idcatart}/show
    defaults: { _controller: "FrontBonPlanBundle:Categoriearticle:show" }
    methods:  GET

categoriearticle_new:
    path:     /newCategorieArticle
    defaults: { _controller: "FrontBonPlanBundle:Categoriearticle:new" }
    methods:  [GET, POST]

categoriearticle_edit:
    path:     /{idcatart}/editCategorieArticle
    defaults: { _controller: "FrontBonPlanBundle:Categoriearticle:edit" }
    methods:  [GET, POST]

categoriearticle_delete:
    path:     /{idcatart}/deleteCategorieArticle
    defaults: { _controller: "FrontBonPlanBundle:Categoriearticle:delete" }
    methods:  DELETE
