back_bon_plan_back_homepage:
    path:     /
    defaults: { _controller: "BackBonPlanBackBundle:Default:index" }
bonplan_admin_template:
    path:     /temp
    defaults: { _controller: BackBonPlanBackBundle:Default:index }
bonplan_prestataire_template:
    path:     /prestataire
    defaults: { _controller: BackBonPlanBackBundle:Default:prestataire }

front_bon_plan_categoriearticle:
        resource: "@FrontBonPlanBundle/Resources/config/routing/categoriearticle.yml"
        prefix:   /categoriearticle

front_bon_plan_categorieevenement:
        resource: "@FrontBonPlanBundle/Resources/config/routing/categorieevenement.yml"
        prefix:   /categorieevenement

listarticles_admin:
    path:     /listArticle
    defaults: { _controller: "FrontBonPlanBundle:Article:indexAdmin" }
    methods:  GET
article_activer:
    path:     /{idarticle}/activerArticle
    defaults: { _controller: "FrontBonPlanBundle:Article:activer" }
    methods:  [GET, POST]
article_desactiver:
    path:     /{idarticle}/desactiverArticle
    defaults: { _controller: "FrontBonPlanBundle:Article:desactiver" }
    methods:  [GET, POST]
article_details:
    path:     /{idarticle}/detailsArticle
    defaults: { _controller: "FrontBonPlanBundle:Article:details" }
    methods:  [GET, POST]

categorieevenement_index:
    path:     /listCategorieEvennement
    defaults: { _controller: "FrontBonPlanBundle:Categorieevenement:index" }
    methods:  GET

categorieevenement_show:
    path:     /{idcatev}/showEvennement
    defaults: { _controller: "FrontBonPlanBundle:Categorieevenement:show" }
    methods:  GET

categorieevenement_new:
    path:     /newEvennement
    defaults: { _controller: "FrontBonPlanBundle:Categorieevenement:new" }
    methods:  [GET, POST]

categorieevenement_edit:
    path:     /{idcatev}/editEvennement
    defaults: { _controller: "FrontBonPlanBundle:Categorieevenement:edit" }
    methods:  [GET, POST]

categorieevenement_delete:
    path:     /{idcatev}/deleteEvennement
    defaults: { _controller: "FrontBonPlanBundle:Categorieevenement:delete" }
    methods:  DELETE


categoriearticle_index:
    path:     /listCategorieArticle
    defaults: { _controller: "FrontBonPlanBundle:Categoriearticle:index" }
    methods:  GET

categoriearticle_show:
    path:     /{idcatart}/show
    defaults: { _controller: "FrontBonPlanBundle:Categoriearticle:show" }
    methods:  GET

categoriearticle_new:
    path:     /newCategorieArticle
    defaults: { _controller: "FrontBonPlanBundle:Categoriearticle:new" }
    methods:  [GET, POST]

categoriearticle_edit:
    path:     /{idcatart}/editCategorieArticle
    defaults: { _controller: "FrontBonPlanBundle:Categoriearticle:edit" }
    methods:  [GET, POST]

categoriearticle_delete:
    path:     /{idcatart}/deleteCategorieArticle
    defaults: { _controller: "FrontBonPlanBundle:Categoriearticle:delete" }
    methods:  DELETE

publicite_index:
    path:     /listpub
    defaults: { _controller: "FrontBonPlanBundle:Publicite:index" }
    methods:  GET

publicite_show:
    path:     /{idpublicite}/showpub
    defaults: { _controller: "FrontBonPlanBundle:Publicite:show" }
    methods:  GET

publicite_new:
    path:     /newpub
    defaults: { _controller: "FrontBonPlanBundle:Publicite:new" }
    methods:  [GET, POST]

publicite_edit:
    path:     /{idpublicite}/editpub
    defaults: { _controller: "FrontBonPlanBundle:Publicite:edit" }
    methods:  [GET, POST]

publicite_delete:
    path:     /{idpublicite}/deletepub
    defaults: { _controller: "FrontBonPlanBundle:Publicite:delete" }
    methods:  DELETE
publicitearticle_index:
    path:     /listpubarticle
    defaults: { _controller: "FrontBonPlanBundle:PubliciteArticle:index" }
    methods:  GET

publicitearticle_show:
    path:     /{id}/showpubarticle
    defaults: { _controller: "FrontBonPlanBundle:PubliciteArticle:show" }
    methods:  GET



publicitearticle_edit:
    path:     /{id}/editpubarticle
    defaults: { _controller: "FrontBonPlanBundle:PubliciteArticle:edit" }
    methods:  [GET, POST]

publicitearticle_delete:
    path:     /{id}/deletepubarticle
    defaults: { _controller: "FrontBonPlanBundle:PubliciteArticle:delete" }
    methods:  DELETE

publicitearticle_activer:
    path:     /{id}/activerpubarticle
    defaults: { _controller: "FrontBonPlanBundle:PubliciteArticle:accept" }
    methods:  [GET, POST]
publicitearticle_refuser:
    path:     /{id}/refuserpubarticle
    defaults: { _controller: "FrontBonPlanBundle:PubliciteArticle:cancel" }
    methods:  [GET, POST]

listuser:
    path:     /listUser
    defaults: { _controller: "FrontBonPlanBundle:User:index" }
    methods:  GET
user_activer:
    path:     /{iduser}/activerUser
    defaults: { _controller: "FrontBonPlanBundle:User:activer" }
    methods:  [GET, POST]
user_desactiver:
    path:     /{iduser}/desactiverUser
    defaults: { _controller: "FrontBonPlanBundle:User:desactiver" }
    methods:  [GET, POST]
categorieevenement_index:
    path:     /listCategorieEvennement
    defaults: { _controller: "FrontBonPlanBundle:Categorieevenement:index" }
    methods:  GET

categorieevenement_show:
    path:     /{idcatev}/showEvennement
    defaults: { _controller: "FrontBonPlanBundle:Categorieevenement:show" }
    methods:  GET

categorieevenement_new:
    path:     /newEvennement
    defaults: { _controller: "FrontBonPlanBundle:Categorieevenement:new" }
    methods:  [GET, POST]

categorieevenement_edit:
    path:     /{idcatev}/editEvennement
    defaults: { _controller: "FrontBonPlanBundle:Categorieevenement:edit" }
    methods:  [GET, POST]

categorieevenement_delete:
    path:     /{idcatev}/deleteEvennement
    defaults: { _controller: "FrontBonPlanBundle:Categorieevenement:delete" }
    methods:  DELETE


categoriearticle_index:
    path:     /listCategorieArticle
    defaults: { _controller: "FrontBonPlanBundle:Categoriearticle:index" }
    methods:  GET

categoriearticle_show:
    path:     /{idcatart}/show
    defaults: { _controller: "FrontBonPlanBundle:Categoriearticle:show" }
    methods:  GET

categoriearticle_new:
    path:     /newCategorieArticle
    defaults: { _controller: "FrontBonPlanBundle:Categoriearticle:new" }
    methods:  [GET, POST]

categoriearticle_edit:
    path:     /{idcatart}/editCategorieArticle
    defaults: { _controller: "FrontBonPlanBundle:Categoriearticle:edit" }
    methods:  [GET, POST]

categoriearticle_delete:
    path:     /{idcatart}/deleteCategorieArticle
    defaults: { _controller: "FrontBonPlanBundle:Categoriearticle:delete" }
    methods:  DELETE
region_new:
    path:     /newRegion
    defaults: { _controller: "FrontBonPlanBundle:Region:new" }
    methods:  [GET, POST]

region_show:
    path:     /{idregion}/showRegion
    defaults: { _controller: "FrontBonPlanBundle:Region:show" }
    methods:  GET
region_index:
    path:     /listRegion
    defaults: { _controller: "FrontBonPlanBundle:Region:index" }
    methods:  GET

region_edit:
    path:     /{idregion}/editRegion
    defaults: { _controller: "FrontBonPlanBundle:Region:edit" }
    methods:  [GET, POST]
region_delete:
    path:     /{idregion}/deleteRegion
    defaults: { _controller: "FrontBonPlanBundle:Region:delete" }
    methods:  DELETE
mailnews_index:
    path:     /maillist
    defaults: { _controller: "FrontBonPlanBundle:Newsletter:listMail" }
    methods:  GET
mailnews_delete_mail_U:
    path:     /{id}/delmuser
    defaults: { _controller: "FrontBonPlanBundle:Newsletter:deleteusermail" }

mailnews_delete_mail_I:
    path:     /{idnewsl}/delminter
    defaults: { _controller: "FrontBonPlanBundle:Newsletter:deleteintermail" }
mailnews_sendallposti:
    path:     /sendallposti
    defaults: { _controller: "FrontBonPlanBundle:Newsletter:envoieallinter" }
    methods:  [GET, POST]
mailnews_sendallpostu:
    path:     /sendallpostu
    defaults: { _controller: "FrontBonPlanBundle:Newsletter:envoiealluser" }
    methods:  [GET, POST]
contact_list:
    path:     /cntlist
    defaults: { _controller: "FrontBonPlanBundle:Contact:listcnt" }
    methods:  GET
mailnews_senduniquser:
    path:     /senduu/{email}
    defaults: { _controller: "FrontBonPlanBundle:Newsletter:envoiuniquser" }
    methods:  [GET, POST]

mailnews_senduniqinter:
    path:     /sendui/{email}
    defaults: { _controller: "FrontBonPlanBundle:Newsletter:envoiuniqinter" }
    methods:  [GET, POST]