tf_user_homepage:
    path:     /home
    defaults: { _controller: tfUserBundle:Default:index }

article_index:
    path:     /listArticle
    defaults: { _controller: "FrontBonPlanBundle:Article:index" }
    methods:  GET

article_show:
    path:     /{idarticle}/showArticle
    defaults: { _controller: "FrontBonPlanBundle:Article:show" }
    methods:  GET

article_new:
    path:     /newArticle
    defaults: { _controller: "FrontBonPlanBundle:Article:new" }
    methods:  [GET, POST]

article_edit:
    path:     /{idarticle}/editArticle
    defaults: { _controller: "FrontBonPlanBundle:Article:edit" }
    methods:  [GET, POST]

article_delete:
    path:     /{idarticle}/deleteArticle
    defaults: { _controller: "FrontBonPlanBundle:Article:delete" }
    methods:  DELETE

evennement_index:
    path:     /listEvenements
    defaults: { _controller: "FrontBonPlanBundle:Evennement:index" }
    methods:  GET

evennement_show:
    path:     /{idev}/showEvenements
    defaults: { _controller: "FrontBonPlanBundle:Evennement:show" }
    methods:  GET

evennement_new:
    path:     /newEvenements
    defaults: { _controller: "FrontBonPlanBundle:Evennement:new" }
    methods:  [GET, POST]

evennement_edit:
    path:     /{idev}/editEvenements
    defaults: { _controller: "FrontBonPlanBundle:Evennement:edit" }
    methods:  [GET, POST]

evennement_delete:
    path:     /{idev}/deleteEvenements
    defaults: { _controller: "FrontBonPlanBundle:Evennement:delete" }
    methods:  DELETE

produit_index:
    path:     /lsp
    defaults: { _controller: "FrontBonPlanBundle:Produit:index" }
    methods:  GET

produit_show:
    path:     /{idproduit}/showpr
    defaults: { _controller: "FrontBonPlanBundle:Produit:show" }
    methods:  GET

produit_new:
    path:     /newPr
    defaults: { _controller: "FrontBonPlanBundle:Produit:new" }
    methods:  [GET, POST]

produit_edit:
    path:     /{idproduit}/editpr
    defaults: { _controller: "FrontBonPlanBundle:Produit:edit" }
    methods:  [GET, POST]

produit_delete:
    path:     /{idproduit}/deletepr
    defaults: { _controller: "FrontBonPlanBundle:Produit:delete" }
    methods:  DELETE

promotion_index:
    path:     /lsprom
    defaults: { _controller: "FrontBonPlanBundle:Promotion:index" }
    methods:  GET

promotion_show:
    path:     /{idpromo}/showprom
    defaults: { _controller: "FrontBonPlanBundle:Promotion:show" }
    methods:  GET

promotion_new:
    path:     /newprom
    defaults: { _controller: "FrontBonPlanBundle:Promotion:new" }
    methods:  [GET, POST]

promotion_edit:
    path:     /{idpromo}/editprom
    defaults: { _controller: "FrontBonPlanBundle:Promotion:edit" }
    methods:  [GET, POST]

promotion_delete:
    path:     /{idpromo}/deleteprom
    defaults: { _controller: "FrontBonPlanBundle:Promotion:delete" }

publicitearticle_index:
    path:     /
    defaults: { _controller: "FrontBonPlanBundle:PubliciteArticle:index" }
    methods:  GET

publicitearticle_show:
    path:     /{id}/show
    defaults: { _controller: "FrontBonPlanBundle:PubliciteArticle:show" }
    methods:  GET

publicitearticle_new:
    path:     /{id}/new
    defaults: { _controller: "FrontBonPlanBundle:PubliciteArticle:new" }
    methods:  [GET, POST]

publicitearticle_edit:
    path:     /{id}/edit
    defaults: { _controller: "FrontBonPlanBundle:PubliciteArticle:edit" }
    methods:  [GET, POST]

publicitearticle_delete:
    path:     /{id}/delete
    defaults: { _controller: "FrontBonPlanBundle:PubliciteArticle:delete" }
    methods:  DELETE


reserver_index:
    path:     /
    defaults: { _controller: "FrontBonPlanBundle:Reserver:index" }
    methods:  GET

reserver_show:
    path:     /{idreservation}/showReservation
    defaults: { _controller: "FrontBonPlanBundle:Reserver:show" }
    methods:  GET

reserver_new:
    path:     /newReservation/{id}
    defaults: { _controller: "FrontBonPlanBundle:Reserver:new" }
    methods:  [GET, POST]

reserver_edit:
    path:     /{idreservation}/editReservation
    defaults: { _controller: "FrontBonPlanBundle:Reserver:edit" }
    methods:  [GET, POST]

reserver_delete:
    path:     /{idreservation}/deleteReservation
    defaults: { _controller: "FrontBonPlanBundle:Reserver:delete" }
    methods:  DELETE

reserver_activer:
    path:     /{idreservation}/activerReservation
    defaults: { _controller: "FrontBonPlanBundle:Reserver:activer" }
    methods:  [GET, POST]

reserver_annuler:
    path:     /{idreservation}/annulerReservation
    defaults: { _controller: "FrontBonPlanBundle:Reserver:annuler" }
    methods:  [GET, POST]

commande_index:
    path:     /lstcmd
    defaults: { _controller: "FrontBonPlanBundle:Commande:index" }
    methods:  GET

commande_show:
    path:     /{idcmd}/show
    defaults: { _controller: "FrontBonPlanBundle:Commande:show" }
    methods:  GET

commande_new:
    path:     /{idproduit}/newcmd
    defaults: { _controller: "FrontBonPlanBundle:Commande:new" }
    methods:  [GET, POST]

commande_newadmin:
    path:     /newcmdadm
    defaults: { _controller: "FrontBonPlanBundle:Commande:newadmin" }
    methods:  [GET, POST]

commande_edit:
    path:     /cmd/{idcmd}/edit
    defaults: { _controller: "FrontBonPlanBundle:Commande:edit" }
    methods:  [GET, POST]

commande_delete:
    path:     /{idcmd}/delete
    defaults: { _controller: "FrontBonPlanBundle:Commande:delete" }
    methods:  [GET, POST, DELETE]
publicitearticle_new:
    path:     /newpubarticle
    defaults: { _controller: "FrontBonPlanBundle:PubliciteArticle:new" }
    methods:  [GET, POST]
