tf_user_homepage:
    path:     /home
    defaults: { _controller: tfUserBundle:Default:index }

article_index:
    path:     /listArticle
    defaults: { _controller: "FrontBonPlanBundle:Article:index" }
    methods:  GET

article_show:
    path:     /{idarticle}/showArticle
    defaults: { _controller: "FrontBonPlanBundle:Article:show" }
    methods:  GET

article_new:
    path:     /newArticle
    defaults: { _controller: "FrontBonPlanBundle:Article:new" }
    methods:  [GET, POST]

article_edit:
    path:     /{idarticle}/editCategorieArticle
    defaults: { _controller: "FrontBonPlanBundle:Article:edit" }
    methods:  [GET, POST]

article_delete:
    path:     /{idarticle}/deleteArticle
    defaults: { _controller: "FrontBonPlanBundle:Article:delete" }
    methods:  DELETE

evennement_index:
    path:     /listEvenements
    defaults: { _controller: "FrontBonPlanBundle:Evennement:index" }
    methods:  GET

evennement_show:
    path:     /{idev}/showEvenements
    defaults: { _controller: "FrontBonPlanBundle:Evennement:show" }
    methods:  GET

evennement_new:
    path:     /newEvenements
    defaults: { _controller: "FrontBonPlanBundle:Evennement:new" }
    methods:  [GET, POST]

evennement_edit:
    path:     /{idev}/editEvenements
    defaults: { _controller: "FrontBonPlanBundle:Evennement:edit" }
    methods:  [GET, POST]

evennement_delete:
    path:     /{idev}/deleteEvenements
    defaults: { _controller: "FrontBonPlanBundle:Evennement:delete" }
    methods:  DELETE
